trans_type_compare = ["", ">", "<", "等于", "后", "前", "不是"]
trans_type_symbol_types = ["", "以后", "以前", "", "及以后", "及以前", "不是"]
trans_type_symbol_types2 = ["", "", "", "", "", "", "不是"]
trans_type_symbol_types3 = ["", "", "", "", "", "", "没有"]
trans_type_symbol = ["", ">", "<", "=", "≥", "≤", "≠"]
or_ = "或"


symbols_int = {
    "is_finalcorner": ["最终弯道", "1"],
    "is_finalcorner_random": ["最终弯道", "1"],
    "order_rate": "名次",
    "is_move_lane": "变换跑道",
    "is_lastspurt": "最后冲刺",
    "distance_rate": "赛程",
    "straight_random": "直线",
    "bashin_diff_behind": ["距离后方马身", "1", trans_type_symbol],
    "bashin_diff_infront": ["距离前方马身", "1", trans_type_symbol],
    "is_overtake": ["准备超越", "1", trans_type_symbol_types3],
    "all_corner_random": ["弯道", "1", trans_type_symbol_types2],
    "down_slope_random": ["下坡", "1", trans_type_symbol_types2],
    "is_finalcorner_laterhalf": ["最终弯道后半段", "1", trans_type_symbol_types2],
    "is_behind_in": ["外道", "1", trans_type_symbol_types2],
    "blocked_front": ["前方有马娘阻挡", "1", trans_type_symbol_types2],
    "up_slope_random": ["上坡", "1", trans_type_symbol_types2],
    "infront_near_lane_time": ["紧跟前方马娘时间", "1", trans_type_symbol_types2],
    "running_style_equal_popularity_one": ["和第一人气的马娘相同作战方式", "1", trans_type_symbol_types2],
    "is_surrounded": ["被包围", "1", trans_type_symbol_types3],
    "phase_laterhalf_random": ["中盘后半段", "1", trans_type_symbol_types2],
    "order_rate_in40_continue": ["名次从比赛开始始终≤40%", "1", trans_type_symbol_types2],
    "is_badstart": ["出栏失误", "1", trans_type_symbol_types3],
    "accumulatetime": ["赛事持续时间", "1", trans_type_symbol],
    "remain_distance": ["剩余距离", "1", trans_type_symbol],
    "blocked_side_continuetime": ["侧面阻挡时间", "1", trans_type_symbol],
    "distance_diff_rate": ["自身处于队伍位置", "1", trans_type_symbol],
    "near_count": ["附近马娘数量", "1", trans_type_symbol],
    "change_order_up_end_after": ["超过人数", "1", trans_type_symbol],
    "running_style_count_same_rate": ["相同跑法马娘数量", "1", trans_type_symbol],
    "running_style_count_senko_otherself": ["先行马娘数量", "1", trans_type_symbol],
    "running_style_count_nige_otherself": ["逃马数量", "1", trans_type_symbol],
    "hp_per": ["体力剩余", "1", trans_type_symbol],
    "post_number": ["栏号", "1", trans_type_symbol],
    "blocked_front_continuetime": ["前方被阻挡时间", "1", trans_type_symbol],
    "temptation_count": ["失去冷静次数", "1", trans_type_symbol],
    "activate_count_start": ["序盘技能发动数量", "1", trans_type_symbol],
    "activate_count_middle": ["中盘技能发动数量", "1", trans_type_symbol],
    "activate_count_end_after": ["终盘技能发动数量", "1", trans_type_symbol],
    "same_skill_horse_count": ["持有相同技能马娘数量（计算自身）", "1", trans_type_symbol],
    "behind_near_lane_time": ["后方贴近时间", "1", trans_type_symbol],
    "running_style_temptation_count_nige": ["失去冷静（掛かり）的逃马数量", "1", trans_type_symbol],
    "running_style_temptation_count_senko": ["失去冷静（掛かり）的先马数量", "1", trans_type_symbol],
    "running_style_temptation_count_sashi": ["失去冷静（掛かり）的差马数量", "1", trans_type_symbol],
    "running_style_temptation_count_oikomi": ["失去冷静（掛かり）的追马数量", "1", trans_type_symbol],
    "popularity": ["人气", "1", trans_type_symbol],
    "temptation_count_behind": ["后方的失去冷静（掛かり）的马数量", "1", trans_type_symbol],
    "temptation_count_infront": ["前方的失去冷静（掛かり）的马数量", "1", trans_type_symbol],
    "running_style_count_sashi_otherself": ["差马数量", "1", trans_type_symbol],
    "running_style_count_oikomi_otherself": ["追马数量", "1", trans_type_symbol],
    "running_style_count_same": ["相同策略马娘数量", "1", trans_type_symbol],
    "overtake_target_time": ["成为被超车目标时间", "1", trans_type_symbol],
    "activate_count_heal": ["耐力恢复技能触发次数", "1", trans_type_symbol],
    "activate_count_all": ["技能触发次数", "1", trans_type_symbol],
    "distance_diff_top": ["和第一名的距离", "1", trans_type_symbol],
    "change_order_up_finalcorner_after": ["最终弯道后超过人数", "1", trans_type_symbol],
    "running_style": {"types": ["", "逃马", "先行", "差行", "追马"], "name": "", "default": 0,
                      "trans_type_symbol": trans_type_symbol_types2},
    "phase_random": {"types": ["序盘", "中盘", "终盘", "终盘后半段"], "name": "", "default": 0,
                     "trans_type_symbol": trans_type_symbol_types},
    "phase": {"types": ["序盘", "中盘", "终盘"], "name": "", "default": 0,
              "trans_type_symbol": trans_type_symbol_types},
    "corner_random": {"types": ["", "第一弯道", "第二弯道", "第三弯道", "第四弯道"], "name": "", "default": 0,
                      "trans_type_symbol": trans_type_symbol_types},
    "season": {"types": ["", "春天", "夏天", "秋天", "冬天", "春天"], "name": "", "default": 0,
               "trans_type_symbol": trans_type_symbol_types},
    "is_basis_distance": {"types": ["赛道长度不为400的倍数", "赛道长度为400的倍数"], "name": "", "default": 0,
                          "trans_type_symbol": trans_type_symbol_types2},
    "rotation": {"types": ["", "右回", "左回"], "name": "", "default": 0,
                 "trans_type_symbol": trans_type_symbol_types2},
    "lane_type": {"types": ["内道", "", ""], "name": "", "default": 0,
                  "trans_type_symbol": trans_type_symbol_types2},
    "slope": {"types": ["", "上坡", "下坡"], "name": "", "default": 0,
              "trans_type_symbol": trans_type_symbol_types2},
    "is_temptation": {"types": ["自身不处于失去冷静", "自身处于失去冷静", ""], "name": "", "default": 0,
                      "trans_type_symbol": trans_type_symbol_types2},
    "straight_front_type": {"types": ["straight_front_type=0", "straight_front_type=1", "向正面直线",
                                      "straight_front_type=3", "straight_front_type=4"], "name": "", "default": 0,
                            "trans_type_symbol": trans_type_symbol_types2},
    "corner": {"types": ["直线", "弯道"], "name": "", "default": 0,
               "trans_type_symbol": trans_type_symbol_types2},
    "distance_type": {"types": ["", "短距离", "英里", "中距离", "长距离"], "name": "", "default": 0,
                      "trans_type_symbol": trans_type_symbol_types},
    "ground_type": {"types": ["", "", "泥地", "", ""], "name": "", "default": 0,
                    "trans_type_symbol": trans_type_symbol_types},
    "ground_condition": {"types": ["", "良场", "稍重场", "重场", "不良场"], "name": "", "default": 0,
                         "trans_type_symbol": trans_type_symbol_types},
    "weather": {"types": ["", "晴天", "阴天", "雨天", "雪天"], "name": "", "default": 0,
                "trans_type_symbol": trans_type_symbol_types},
}

symbols_none = {
    "change_order_onetime": "排名更改",
    "bashin_diff_behind": "距离后方马身",
    "order": "名次",
    "always": "",
    "random_lot": "触发概率",
    "track_id": "竞马场",
    "distance_rate_after_random": "赛程≥{}%, 随机位置",
}

sp = {
    "final_straight": "最终直线"
}

tracks = {
    "10001": "札幌",
    "10002": "函馆",
    "10003": "新潟",
    "10004": "福岛",
    "10005": "中山",
    "10006": "东京",
    "10008": "京都",
    "10007": "中京",
    "10009": "阪神",
    "10010": "小仓",
    "10101": "大井",
}
